name: discord_api_client
description: An API Client for Discord, written in Dart.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  http: ^1.0.0
  json_utils: ^0.0.0-a1

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.0.0
